mypage/urls.py
from django.urls import path
from. import views

app_name = 'mypage'

urlpatterns = [
    path('', views.MyPageView.as_view(), name='mypage'),
    path('upload/', views.upload_file, name='upload'),
    path('upload/success/', views.upload_success, name='success'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('search/', include('search.urls')),
    path('account/', include('account.urls')),
    # path('account/', include('allauth.urls')),
    path('mypage/', include('mypage.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path
from . import views

from django.conf.urls.static import static
from django.conf import settings

from .api.views import TrainList

app_name = 'search'

urlpatterns = [
    path('', views.Search, name='search'),
    path('results/', views.SearchResult, name='results'),
    # path('api/v1/trainings/', TrainList.as_view()),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mypage/models.py
from django.db import models
from django.contrib.auth.models import User

class Training_List(models.Model):
    owner = models.ForeignKey(User, related_name="owner", on_delete=models.CASCADE)
    number = models.CharField(max_length=400)
    name = models.CharField(max_length=300)
    auth = models.CharField(max_length=200)
    period_st = models.DateField()
    period_end = models.DateField()
    time = models.DurationField()
    type = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Excel_File(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    upload = models.FileField(upload_to='uploads/')

mypage/forms.py
from django import forms
from .models import Excel_File

class UploadFileForm(forms.ModelForm):
    class Meta:
        model = Excel_File
        fields = ['upload']

mypage/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .forms import UploadFileForm
from .methods import mk_mytraining, mk_db
from .models import Training_List, Excel_File

from django.views.generic import FormView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.core.paginator import Paginator

class MyPageView(LoginRequiredMixin, FormView):
    login_url = 'account:login'
    form_class = UploadFileForm
    template_name = 'mypage/mypage.html'
    success_url = '/mypage/'


    def get_context_data(self, **kwargs):
        # context 얻기 위해 먼저 기본 구현을 호출
        context = super().get_context_data(**kwargs)
        training_list = Training_List.objects.filter(owner_id=self.request.user.id)
        paginator = Paginator(training_list, 10)
        page = self.request.GET.get('page', 1)
        page_obj = paginator.get_page(page)
        context['training_list'] = page_obj

        return context

    # def form_valid(self, form):
    #     owner = self.request.user
    #     word = form.cleaned_data.get('word')
    #     keyword, created = Keyword.objects.get_or_create(word=word)
    #     keyword.owner.add(owner)
    #     return super().form_valid(form)

@login_required(login_url='account:test')
def upload_file(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            excel = form.save(commit=False)
            excel.owner = request.user
            excel.save()
            xlsx = request.FILES['upload']
            df = mk_mytraining(xlsx)
            Training_List.objects.all().delete()
            for i in range(len(df)):
                Training_List.objects.create(
                    owner=request.user,
                    number=df.iloc[i]['number'],
                    name=df.iloc[i]['name'],
                    auth=df.iloc[i]['auth'],
                    period_st=df.iloc[i]['period_st'],
                    period_end=df.iloc[i]['period_end'],
                    time=df.iloc[i]['time'],
                    type=df.iloc[i]['type']
                )
            return HttpResponseRedirect('success/')
    else:
        form = UploadFileForm()

    return render(request, 'mypage/mypage.html', {'form': form})


@login_required(login_url='account:test')
def upload_success(request):
    training_list = Training_List.objects.filter(owner=request.user)
    form = UploadFileForm()

    paginator = Paginator(training_list, 10)

    page = request.GET.get('page', 1)
    page_obj = paginator.get_page(page)

    context = {'training_list': page_obj, 'form': form}

    return render(request, 'mypage/mypage.html', context)

templates/mypage/mypage.html
{% extends "base.html" %}
{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

<h4>내가 들은 연수</h4>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">연수이수번호</th>
      <th scope="col">연수과정명</th>
      <th scope="col">연수기관</th>
      <th scope="col">연수시간</th>
      <th scope="col">2021년 연수시간누계</th>
    </tr>
  </thead>
  <tbody>
    {% load mypage_extras %}
    {% with tp=training_list.number|add:-1|multi:10 %}
    {% for train in training_list %}
    <tr>
      <th scope="row">{{ forloop.counter|add:tp }}</th>
      <td>{{ train.number }}</td>
      <td>{{ train.name }}</td>
      <td>{{ train.auth }}</td>
      <td>{{ train.time }}</td>
      <td></td>
    </tr>
    {% endfor %}
    {% endwith %}
  </tbody>
</table>

<ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if training_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ training_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in training_list.paginator.page_range %}
        {% if page_number >= training_list.number|add:-5 and page_number <= training_list.number|add:5 %}
            {% if page_number == training_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if training_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>

<form method="post" action="{% url 'mypage:upload' %}" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="제출">
</form>

<br/>
<br/>
<br/>

<h4>법정 의무 연수 이수 현황</h4>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">#</th>
      <th scope="col">인정 교육</th>
      <th scope="col">필요 이수 시간</th>
      <th scope="col" style="color:red">나의 이수 현황</th>
      <th scope="col"style="color:blue">관련 연수</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>교육활동 침해행위 예방교육</td>
      <td>연 1회 이상</td>
      <td>4시간/4시간</td>
      <td colspan="1">
        <a href="{% url 'search:results' %}?kw=침해&site_all=on&choice_site1=on&choice_site2=on" target="_blank">연수 목록 ↗</a>
      </td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>긴급복지 신고의무교육</td>
      <td>연 1시간 이상</td>
      <td>4시간/4시간</td>
      <td>@instagram</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>부정청탁 및 금품 수수 금지교육</td>
      <td>연1회 2시간 이상</td>
      <td>4시간/4시간</td>
      <td>@twitter</td>
    </tr>
      <tr>
      <th scope="row">4</th>
      <td>부패방지 교육</td>
      <td>연1회 2시간 이상</td>
      <td>4시간/4시간</td>
      <td>@facebook</td>
    </tr>
      <tr>
      <th scope="row">5</th>
      <td>생명존중 및 자살 예방교육</td>
      <td>연 4시간 이상</td>
      <td>4시간/4시간</td>
      <td colspan="1">
        <a href="{% url 'search:results' %}?kw=자살&site_all=on&choice_site1=on&choice_site2=on" target="_blank">연수 목록 ↗</a>
      </td>
    </tr>
  </tbody>
</table>

{% endblock content %}

</body>
</html>