account/urls.py
from django.urls import path
from . import views
from django.views.generic.base import TemplateView


app_name = 'account'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
]

mypage/urls.py
from django.urls import path
from. import views

app_name = 'mypage'

urlpatterns = [
    path('', views.MyPageView.as_view(), name='mypage'),
    path('upload/', views.upload_file, name='upload'),
    path('upload/success/', views.upload_success, name='success'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('search/', include('search.urls')),
    path('account/', include('account.urls')),
    # path('account/', include('allauth.urls')),
    path('mypage/', include('mypage.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path
from . import views

from django.conf.urls.static import static
from django.conf import settings

from .api.views import TrainList

app_name = 'search'

urlpatterns = [
    path('', views.Search, name='search'),
    path('results/', views.SearchResult, name='results'),
    # path('api/v1/trainings/', TrainList.as_view()),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="kor">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <title>{% block title %}Search4Teacher{% endblock title %}</title>
</head>

<body>
    <div id="sidebar">{% block sidebar %}

        <a href="/"># Home</a>
        <a href="/admin/"># Admin</a>&nbsp;&nbsp;&nbsp;

        {% if user.is_authenticated %}
            <span style="font-size:18px;">{{ user.username }}님, 안녕하세요! &nbsp;<a href="{% url 'account:logout' %}">(# 로그아웃)</a></span>
        {% else %}
            <a href="{% url 'account:register' %}"># 회원가입</a>
            <a href="{% url 'account:login' %}"># 로그인</a>
        {% endif %}
        <br/><br/><br/>
    {% endblock sidebar %}</div>

    <div id="content">
        {% block content %}{% endblock content %}
    </div>
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% block title %}S4T HOME{% endblock title%}
{% block content %}
<ul>
    <li><a href="{% url 'search:search' %}">연수 검색</a></li>
    <li><a href="{% url 'mypage:mypage' %}">나의 연수 이수 상황</a></li>
</ul>

{% endblock content %}


<!--    <ul>-->
<!--        {% for app in app_list %}-->
<!--            {% with app|add:":"|add:"index"|lower|cut:" " as urlvar %}-->
<!--            <li><h2><a href="{% url urlvar %}">{{app}}</a></h2></li>-->
<!--            {% endwith %}-->
<!--        {% endfor %}-->
<!--    </ul>-->